SELECT
    rh.HISTORY_ID,
    FLOOR(
        c.DAILY_FEE * (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1) * 
        CASE
            WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 90 THEN (1 - (SELECT DISCOUNT_RATE / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'))
            WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 30 THEN (1 - (SELECT DISCOUNT_RATE / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'))
            WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 7 THEN (1 - (SELECT DISCOUNT_RATE / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'))
            ELSE 1
        END
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR c
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY rh ON c.CAR_ID = rh.CAR_ID
WHERE
    c.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    rh.HISTORY_ID DESC;