SELECT 
    APPOINTMENT.APNT_NO,
    PATIENT.PT_NAME,
    PATIENT.PT_NO,
    APPOINTMENT.MCDP_CD,
    DOCTOR.DR_NAME,
    APPOINTMENT.APNT_YMD
FROM APPOINTMENT
JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE 
    APPOINTMENT.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
    AND APPOINTMENT.APNT_CNCL_YN = 'N'
    AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APPOINTMENT.APNT_YMD ASC;