SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX_YEARLY_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM 
    (SELECT 
        ID,
        SIZE_OF_COLONY,
        DIFFERENTIATION_DATE,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_YEARLY_SIZE
    FROM 
        ECOLI_DATA
    ) AS SUBQUERY
ORDER BY 
    YEAR ASC,
    YEAR_DEV ASC;
