SELECT DISTINCT(R.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
ON C.CAR_ID = R.CAR_ID
WHERE C.CAR_TYPE = '세단' AND DATE_FORMAT(R.START_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CAR_ID DESC;